config/routes.rb
Clockd::Application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :timecards, except: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Timecard, user_id: user.id
  end
end

app/models/timecard.rb
class Timecard < ActiveRecord::Base
  
  belongs_to :user
  
  validates_presence_of :title 
  validate :future_completed_date 
  validates_presence_of :user
  
  private 
  
  def future_completed_date 
    if !completed.blank? && completed > Date.today 
      self.errors.add(:completed, "can't be in the future.") 
    end 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
  has_many :timecards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  
  layout :layout_by_controller 
  
  protected 
  
  def layout_by_controller 
    devise_controller? ? 'devise' : 'application' 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @timecards = Timecard.accessible_by(current_ability)
  end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  
  def new
    @timecard = Timecard.new
    render :show_form
  end
  
  def create     
    @timecard = Timecard.new(timecard_params)    
    @timecard.user = current_user
    authorize! :create, @timecard
    save_timecard
  end   
  
  def edit
    @timecard = Timecard.find(params[:id])
    authorize! :edit, @timecard
    render :show_form
  end
    
  def update 
    @timecard = Timecard.find(params[:id]) 
    @timecard.update_attributes(timecard_params)
    authorize! :update, @timecard
    save_timecard
  end  
  
  def destroy 
    @timecard = Timecard.find(params[:id]) 
    authorize! :destroy, @timecard
    @timecard.destroy 
    @timecards = Timecard.accessible_by(current_ability)
  end
  
  private
  
  def save_timecard 
    if @timecard.save 
      @timecards = Timecard.accessible_by(current_ability)
      render :hide_form 
    else 
      render :show_form 
    end 
  end
  
  def timecard_params     
    params.require(:timecard).permit(:title, :note, :completed)   
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Clockd      
    = stylesheet_link_tag    "application", media: "all"     
    = javascript_include_tag "application"     
    = csrf_meta_tags    
  %body     
    .row-fluid       
      .span10.offset1         
        .hero-unit.text-center           
          %h1             
            Clockd          
          %p             
            Welcome to Clockd, an easy timecard application.
          = link_to 'New timecard', new_timecard_path, class: 'btn btn-primary input-large', remote: true
          .text-center 
            %strong= current_user.email 
          .text-center 
            = link_to 'logout', destroy_user_session_path, method: :delete
        = yield 

app/views/layouts/devise.html.haml
!!! 
%html 
  %head 
    %title Clockd 
    = stylesheet_link_tag "application", media: "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  %body 
    .row-fluid 
      .span10.offset1 
        .hero-unit.text-center 
          %h1 
            Clockd 
          %p 
            Welcome to Clockd, an easy timecard application. 
    .row-fluid 
      .span4.offset4 
        = yield

app/views/pages/home.html.haml
#timecard-list
  = render partial: 'timecards/timecard_list', locals: {timecards: @timecards} 
#modal.modal.fade

app/views/shared/_flash.html.haml
- flash.each do |type, value| 
  .flash{ :class => type.to_s } 
    = value

app/views/timecards/_timecard_form.html.haml
.modal-header
  %h1 
    = timecard.new_record? ? 'New Timecard' : "Editing timecard #{timecard.title}"
= simple_form_for timecard, class: 'clearfix', remote: true do |f|   
  .modal-body     
    = f.input :title     
    = f.input :note     
    = f.input :completed, as: :string, input_html: { class: 'datetimepicker', value: timecard.completed.present? ? localize(timecard.completed, format: '%m/%d/%Y at %I:%M') : nil }
  .modal-footer     
    = f.submit 'Save', class: 'btn btn-primary'

app/views/timecards/_timecard_list.html.haml
- if timecards.empty?     
  %span.text-warning There are no timecards here!   
- else
  %div.table-responsive
    %table.table.table-hover.table-bordered     
      %thead         
        %tr           
          %th Title           
          %th Created at           
          %th Completed
          %th Actions
      %tbody         
        - timecards.each do |timecard|           
          %tr             
            %td               
              %strong= timecard.title             
            %td.text-info= timecard.created_at             
            %td.text-success= timecard.completed
            %td                
              = link_to edit_timecard_path(timecard), remote: true do 
                %i.icon-edit
                %span Edit or Clock Out
              = link_to timecard_path(timecard), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete timecard #{timecard.title}?"} do 
                %i.icon-remove
                %span Remove 

app/views/timecards/destroy.js.erb
$('#timecard-list').html('<%= j(render partial: 'timecard_list', locals: {timecards: @timecards})%>');

app/views/timecards/edit.js.erb
m = $('#modal'); 
m.html('<%= j(render partial: 'timecard_form', locals: {timecard: @timecard})%>'); 
m.modal('show'); 
$('#modal').integrateDatetimepicker();

app/views/timecards/hide_form.js.erb
$('#timecard-list').html('<%= j(render partial: 'timecards/timecard_list', locals: {timecards: @timecards}) %>'); 
$('#modal').modal('hide');

app/views/timecards/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'timecard_form', locals: {timecard: @timecard}) %>'); 
m.modal('show');
$('#modal').integrateDatetimepicker();